ALTER TABLE Evenement RENAME COLUMN Titre TO Nom;

ALTER TABLE Users DROP COLUMN ID;

ALTER TABLE Users ADD (
    ID number(10) GENERATED BY DEFAULT ON NULL AS IDENTITY
);

ALTER TABLE Foyer MODIFY(
    Id DEFAULT SEQFOYER.nextval
);

ALTER TABLE Citoyen MODIFY(
    Id DEFAULT SEQCITOYEN.nextval,
    email NULL,
    CIN NULL,
    Prenoms NULL,
    LieuCIN NULL,
    DateNaissance NOT NULL,
    LieuNaissance NOT NULL
);

ALTER TABLE RequeteCitoyen MODIFY(
    Id DEFAULT SEQREQUETECITOYEN.nextval
);

ALTER TABLE RequeteCitoyen ADD(
    status number(1),
    Check(status in (0,1))
);

ALTER TABLE PrecenceEvenement MODIFY(
    Id DEFAULT SEQPRESENCEEVENEMENT.nextval
);

ALTER TABLE ImpotFoyer MODIFY 
Id DEFAULT SEQIMPOTFOYER.nextval;

ALTER TABLE ImpotFoyer ADD (
    datePaiement Date NOT NULL
);
    

insert into Evenement (id, nom, dateEvent, details, lieu) values (SEQEVENEMENT.nextval, 'Fanadiovana faobe', to_date('2023-09-31', 'yyyy-MM-dd'), null, 'FJKM Ambatomaro');