CREATE TABLE Foyer (
    id number(8) GENERATED BY DEFAULT ON NULL AS IDENTITY constraint pk_foyer_foyedid primary key,
    Adresse varchar2(30) NOT NULL UNIQUE,
    Longitude number(10,6),
    Latitude number(10,6)
);


CREATE TABLE Users (
    id number(8) GENERATED BY DEFAULT ON NULL AS IDENTITY constraint pk_user_userid primary key,
    email varchar(80) NOT NULL,
    password varchar(150) NOT NULL,
    role varchar(20) NOT NULL,
    UNIQUE(email),
    FoyerId number(8),
    FOREIGN KEY(FoyerId) REFERENCES Foyer(id)
);

CREATE TABLE Citoyen (
    id number(8) GENERATED BY DEFAULT ON NULL AS IDENTITY constraint pk_citoyen_citoyenid primary key,
    Nom varchar(50) NOT NULL,
    Prenoms varchar(50),
    DateNaissance date NOT NULL,
    LieuNaissance varchar(25) NOT NULL,
    Sexe varchar(10) NOT NULL,
    constraint chk_citoyen_sexe check(Sexe in ('Homme','Femme')),
    CIN varchar(12),
    DateCIN date,
    LieuCIN varchar(25),
    Metier varchar(25),
    NomPere varchar(80),
    NomMere varchar(80),
    DateInscription date,
    FoyerId Fnumber(8) NOT NULL,
    FOREIGN KEY(FoyerId) REFERENCES Foyer(id),
    actif char(1),
    constraint chk_citoeyn_actif check(Actif in ('T','F'))
);

ALTER TABLE Foyer
ADD (
    ChefFoyer number(8),
    CONSTRAINT fk_chefFoyer FOREIGN KEY(ChefFoyer) REFERENCES Citoyen(id)
);


-- En relation avec le citoyen
CREATE TABLE Document (
    id number(8) GENERATED BY DEFAULT ON NULL AS IDENTITY constraint pk_document_documentid primary key,
    Nom varchar(50) NOT NULL,
    Url varchar(100),
    CitoyenID number(8),
    FOREIGN KEY(CitoyenID) REFERENCES Citoyen(id)
);

CREATE TABLE Requete(
    id number(8) GENERATED BY DEFAULT ON NULL AS IDENTITY constraint pk_requete_requeteid primary key,
    TypeRequete varchar(50) NOT NULL,
    Frais number NOT NULL,
    constraint chk_requete_frais check(Frais > 100)
);

CREATE TABLE RequeteCitoyen (
    id number(8) GENERATED BY DEFAULT ON NULL AS IDENTITY constraint pk_requetecitoyen_id primary key,
    CitoyenID number(8) NOT NULL,
    RequeteID number(8) NOT NULL,
    FOREIGN KEY(CitoyenID) REFERENCES Citoyen(id),
    FOREIGN KEY(RequeteID) REFERENCES Requete(id),
    DateRequete date NOT NULL
);


-- En relation avec le foyer
CREATE TABLE Impot (
    id number(8) GENERATED BY DEFAULT ON NULL AS IDENTITY constraint pk_impot_impotid primary key,
    annee number(4) NOT NULL,
    constraint chk_impot_annee check(annee > 2020),
    mois number(4) NOT NULL,
    constraint chk_impot_mois check(mois between 1 and 12),
    foyerID number(8) NOT NULL,
    FOREIGN KEY(FoyerID) REFERENCES Foyer(id),
    unique(annee, mois, foyerID)
);

CREATE TABLE PresenceEvenement (
    FoyerID number(8) NOT NULL,
    FOREIGN KEY(FoyerID) REFERENCES Foyer(id),
    EvenementID varchar(50) NOT NULL,
    Constraint pk_foyer_evenement primary key(FoyerId, EvenementID),
    DatePresence date  NOT NULL
);


-- En relation avec le citoyen et le foyer
CREATE TABLE Mouvement (
    id number(8) GENERATED BY DEFAULT ON NULL AS IDENTITY constraint pk_mouvement_mouvementid primary key,
    CitoyenID number(8) NOT NULL,
    FoyerID number(8) NOT NULL,
    FOREIGN KEY(CitoyenID) REFERENCES Citoyen(id),
    FOREIGN KEY(FoyerID) REFERENCES Foyer(id),
    Cause varchar(30)
);




